export const messages = {
  FIRST_TIME_USER: '🌈  Hello and welcome to the National Hope Service. We\'ve created this channel to help keep the spirits of our NHS workers lifted as this pandemic drags on. We may be coming out of lockdown but our NHS heroes are still on the front-line... \n\n❓First up, do you work for the NHS or do you want to send a message of support? \n\nJust type \'NHS\' or \'Support\'...',
  FIRST_TIME_PUBLIC_USER_IMAGE: 'https://s3-eu-west-1.amazonaws.com/voxly.client.skills/assets/NHS-BOTS/img/welcome_img.png',
  FIRST_TIME_PUBLIC_USER_GREETING: 'Thanks for getting involved and supporting our amazing NHS 💙 \n\nIn 1914, people at home sent letters to their loved ones on the front to keep their spirits up. In 2020, our NHS army needs some of the same love. The lockdown may be changing for us but for them, this crisis drags on. We can\'t forget about them. \n\nFirst up, I need to confirm your age. Are you over 18?',
  FIRST_TIME_NHS_USER_IMAGE: 'https://s3-eu-west-1.amazonaws.com/voxly.client.skills/assets/NHS-BOTS/img/welcome_doc_img.png',
  FIRST_TIME_NHS_USER_GREETING: 'Hello you absolute hero! \n\nYou are not alone! 70 million people are standing right behind you.💙 \n\nWe’re so grateful for what you are doing. The sacrifice that you and your families are making has not gone unnoticed. 🌈 \n\nIn this channel you can hear voice Notes from the Nation: short messages of support from the members of the public to keep you going. \n\n🔗Check this link for details on how it works: thenationalhopeservice.com \n\nAre you happy with this, and ready to get going?',
  NHS_INVALID_ANSWER_CONSENT: '🤔 Sorry, I’m not sure I understood you. I need to confirm that you’re keen to use this service. Just type ‘Yes’ or ‘No’ to proceed.',
  PUBLIC_INVALID_ANSWER_CONSENT: '🤔 Sorry, I’m not sure I understood you. Are you happy to continue? Just type ‘Yes’ or ‘No’',
  PROFILE_TYPE_ERROR: 'If you work for the NHS, just type \'NHS\' to get started. 💙 \n\nOr, if you want to spread the love and send a voice note of thanks, type \'Support\' \n\nEither way, you’re a hero!',
  USER_IS_UNDER_18: 'Ok, thanks for letting us know. Unfortunately this service is not available for those under the age of 18. Team up with an adult if you’d like to get involved, or pass on this opportunity to others who might be interested. Thanks again and stay safe! 💖',
  USER_IS_OVER_18: 'Excellent! Here’s a few more things to consider before we jump in: \n\n🧐 Your number will be stored by us, but we can delete it anytime, just type \'Delete\'. \n\n🎙Your voice note will also be stored and screened by really humans before sending it over to our NHS heroes. \n\n➡️ We can’t control or stop recipients forwarding on your voice notes to others. But if they are positive messages, hopefully that’s ok. \n\n🔗Check out more details here: thenationalhopeservice.com/privacy-policy \n\nAre you happy to continue? Type \'Yes\' if you are.',
  USER_AGE_INVALID_ANSWER: '🤔 Sorry, I’m not sure I understood you. Just type ‘Yes’ of you are over 18 or ‘No’ if you are not yet 18.',
  USER_CONSENT_YES: 'Time to send a voice note and brighten someone’s day! They won\'t be able to respond but trust us, it’s amazingly powerful for our NHS heroes to actually hear you speaking your support.  🙏 Words of wisdom, encouragement or just a simple thank you will all go down a treat! \n\nOver to you...🎤',
  USER_CONSENT_NO: 'No worries, ping us here, if you change your mind. Stay indoors and stay safe.🏠',
  NHS_CONSENT_YES: 'Great! To make sure the messages get to the right place, I need to confirm that you’re working for the NHS. \n\n💌What is your work email? \n\nWe will send you a 5-digit code to verify your email account (don’t worry, we won’t store it or use it for any other purposes)',
  NHS_CONSENT_NO: 'No worries, ping us here, if you change your mind. Stay safe 🏠',
  EMAIL_AUTHORIZATION_SENT: 'Thanks! We’ve sent you an email. \n\nWhat is your 5-digit code?',
  GENERIC_EMAIL_VALIDATION_ERROR: 'Hmm, that doesn\'t look like a valid NHS email address. Try typing that again...',
  NHS_EMAIL_VALIDATION_ERROR: 'Look like that one\'s still not working. You need to have a valid @nhs email. Type it again',
  AUDIO_MESSAGE_CONFIRMATION_1: 'Thank you 👍 We\'ll make sure the people who really need this get to hear it. Send us another voice note or share this number with others to help us collect as many as possible. ☎️  \n\nIn the meantime, stay indoors and stay safe. 💞🏡',
  AUDIO_MESSAGE_CONFIRMATION_2: 'Keeping all our key workers\' spirits lifted is so important in this time. You\'ll have just helped them feel less alone. ☎️ Please share this number with others to help us keep collecting these lovely messages for the people who need to hear them.',
  AUDIO_MESSAGE_CONFIRMATION_3: 'We might be finding a new normal but our key workers\' will be fighting this battle for long time to come. Knowing that they have your support will mean the world 🌍 Thank you.',
  AUDIO_MESSAGE_CONFIRMATION_4: 'Thanks so much 🌈 This will be sent to those you need to hear it most. Send us another note if you fancy.',
  AUDIO_MESSAGE_CONFIRMATION_REJECTED: 'No worries. Give it another go now you’ve had a practise run! 🎤',
  AUDIO_MESSAGE_CONFIRMATION_INCORRECT_ANSWER: 'Just type \'Yes\' if you\'re happy for your voice note to be sent or No to record another one.',
  RETURNING_PUBLIC_USER_TEXT: '🌈 Let’s spread the love! Record your voice message for our wonderful NHS staff. \n\nJust like last time: \n\n⏱The notes can be up to 20 seconds long \n\n❤️Keep it positive to lift the spirits of those working hard on the frontline to keep us all safe. \n\nOver to you 🎤',
  USER_HAS_LEFT_THREE_VOICE_RECORDINGS: 'Thanks for sharing the love! \n💖We can only accept 3 voice notes a day per person. \nCome back again tomorrow to send another if you’d like to though! 🎤',
  USER_HAS_LEFT_THREE_VOICE_RECORDINGS_RETURNING_TEXT: 'Love the enthusiasm! But you\'ve maxed out for today on your 3 voice notes. Come back again tomorrow to send more. In the mean-time, please share this number with others to keep spreading the love🌈',
  USER_LEFT_VOICE_RECORDING_NOT_CONFIRMED: 'Nice one! Are you happy for this to be shared with our NHS front-line? Type \'Yes\' or \'No\'.',
  DIFFERENT_FILE_TYPE: [
    '👀 This looks like something else. For now, you can only send us voice notes up to 20 seconds long. \n\n Just hold down the record button and then hit send. Give it another go! 🎤',
    '👀 Hhmm, we\'re only looking for 20 second voice notes for now. Try that again 🎤',
    '🌈 Send our NHS heroes a real, spoken thank you. Just hold down the record button and then hit send...'
  ],
  NO_RECORDS: 'Unfortunatelly there are no records at the moment. Try another time.',
  VERIFICATION_CODE_VALID: '✅ Perfect! We’ve already got a note ready for you...',
  FINAL_MESSAGE_AFTER_FIRST_RECORD: 'Hopefully that brightened your day a bit. Whenever you want to hear another one, just send an emoji. Keep going, you are incredible! 🌈',
  VERIFICATION_CODE_INVALID_1: '❌ Hhmm. That doesn’t look like a valid code. Try typing it again...',
  VERIFICATION_CODE_INVALID_2: '❌ That code still doesn’t look right. Please type it again...',
  VERIFICATION_CODE_INVALID_3: '❌ Ok, let’s try this a different way. Type your email address again and we’ll send you another code to try...',
  HELP: 'Having problems eh? If you\'re getting stuck, head to the help page: thenationalhopeservice.com/help If you want to delete your account (which we hope you don\'t), just type \'Delete\' and poof, it\'ll be gone.',
  USER_REGISTRATION_NOT_COMPLETE: 'Registration is not complete. Start again. Just type "start".',
  UNHANDLED_MESSAGE_TYPE: '👀 This looks like something else. \n\n For now, you can only send us voice notes up to 20 seconds long or text. \n\nGive it another go! 🎤',
  WHAT_IS_THIS: 'This is just the UK’s small way of saying thank you for all that you do. By sending an emoji, you can request another message of thanks and support, all recorded and submitted by the public. It’s only a little gesture, but hopefully it’ll help you get through the day. Thank you for everything.',
  NHS_USER_REQUESTS_VOICE_MESSAGE: [
    'You\'re never alone. Another note from the nation coming up:',
    'We know it\'s tough. We hope this message is what you need to hear...',
    'Remember that we’re all with you.',
    'You can do this. Hope this message helps....',
    'Keep going. You are incredible.',
    'Take it one day at a time...'
  ]
}
